/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * https://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <curl/curl.h>
#include <string.h>
#include <stdlib.h>

size_t header_callback(char *buffer, size_t size, size_t nitems, void *userdata)
{
    (void) userdata;
    size_t len = size * nitems;
    char *head = malloc(len + 1);
    memcpy(head, buffer, len);
    head[len] = '\0';
    /*
    if(strchr(head, '\r'))
    {
        printf("has CR, ");
    }
    if(strchr(head, '\n')) // strchrとかstrpbrk
    {
        printf("has LF, ");
    }
    */
    char *crlf = strpbrk(head, "\r\n");
    if (crlf != NULL)
        *crlf = '\0';
    if (strlen(head) != 0)
        printf("%s\n", head);
    free(head);
    return len;
}

int main(void)
{
    CURLcode ret;
    CURL *hnd;

    hnd = curl_easy_init();
    curl_easy_setopt(hnd, CURLOPT_BUFFERSIZE, 102400L);
    curl_easy_setopt(hnd, CURLOPT_URL, "http://xiwayy2kn32bo3ko.onion/tor/subject.txt");
    curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
    curl_easy_setopt(hnd, CURLOPT_NOBODY, 1L);
    curl_easy_setopt(hnd, CURLOPT_CUSTOMREQUEST, "HEAD");
    curl_easy_setopt(hnd, CURLOPT_HEADERFUNCTION, header_callback);
    curl_easy_setopt(hnd, CURLOPT_PROXY, "socks5h://localhost:9050");
    curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.68.0");
    curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
    curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);
    curl_easy_setopt(hnd, CURLOPT_SSH_KNOWNHOSTS, "/home/teruteru128/.ssh/known_hosts");
    curl_easy_setopt(hnd, CURLOPT_FILETIME, 1L);
    curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);

    /* Here is a list of options the curl code used that cannot get generated
         as source easily. You may select to either not use them or implement
         them yourself.

    CURLOPT_WRITEDATA set to a objectpointer
    CURLOPT_INTERLEAVEDATA set to a objectpointer
    CURLOPT_WRITEFUNCTION set to a functionpointer
    CURLOPT_READDATA set to a objectpointer
    CURLOPT_READFUNCTION set to a functionpointer
    CURLOPT_SEEKDATA set to a objectpointer
    CURLOPT_SEEKFUNCTION set to a functionpointer
    CURLOPT_ERRORBUFFER set to a objectpointer
    CURLOPT_STDERR set to a objectpointer
    CURLOPT_HEADERFUNCTION set to a functionpointer
    CURLOPT_HEADERDATA set to a objectpointer

    */

    ret = curl_easy_perform(hnd);

    curl_easy_cleanup(hnd);
    hnd = NULL;

    return (int)ret;
}
/**** End of sample code ****/
