/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * https://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#include <config.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <curl/curl.h>

struct count
{
  struct tm time;
  size_t count;
};

static size_t write_callback(char *ptr, size_t size, size_t nmemb, void *stream)
{
  struct count *count = (struct count *)stream;
  strptime(ptr + 9, "%F %T", &count->time);
  count->count = strtoul(ptr + 39, NULL, 10);
  return size * nmemb;
}

int main(int argc, char *argv[])
{
  curl_global_init(CURL_GLOBAL_ALL);
  CURLcode ret;
  CURL *hnd = curl_easy_init();
  struct count count;
  curl_easy_setopt(hnd, CURLOPT_BUFFERSIZE, 102400L);
  curl_easy_setopt(hnd, CURLOPT_URL, "https://nyanpass.com/api.php/get_count");
  curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 1L);
  curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.68.0");
  curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
  curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);
  curl_easy_setopt(hnd, CURLOPT_SSH_KNOWNHOSTS, "/home/teruteru128/.ssh/known_hosts");
  curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);
  curl_easy_setopt(hnd, CURLOPT_WRITEDATA, &count);
  curl_easy_setopt(hnd, CURLOPT_WRITEFUNCTION, write_callback);

  /* Here is a list of options the curl code used that cannot get generated
     as source easily. You may select to either not use them or implement
     them yourself.

  CURLOPT_WRITEDATA set to a objectpointer
  CURLOPT_INTERLEAVEDATA set to a objectpointer
  CURLOPT_WRITEFUNCTION set to a functionpointer
  CURLOPT_READDATA set to a objectpointer
  CURLOPT_READFUNCTION set to a functionpointer
  CURLOPT_SEEKDATA set to a objectpointer
  CURLOPT_SEEKFUNCTION set to a functionpointer
  CURLOPT_ERRORBUFFER set to a objectpointer
  CURLOPT_STDERR set to a objectpointer
  CURLOPT_HEADERFUNCTION set to a functionpointer
  CURLOPT_HEADERDATA set to a objectpointer

  */

  char buf[BUFSIZ];
  struct timespec spec = {.tv_sec = 1, .tv_nsec = 0};
  struct timespec rem;
  for (size_t i = 0; i < 3600; i++)
  {
    ret = curl_easy_perform(hnd);
    if (ret != CURLE_OK)
      break;
    strftime(buf, BUFSIZ, "%FT%T+09:00", &count.time);
    printf("%s, %zu\n", buf, count.count);
    nanosleep(&spec, &rem);
  }

  curl_easy_cleanup(hnd);
  hnd = NULL;

  curl_global_cleanup();
  return (int)ret;
}
/**** End of sample code ****/
