name: C/C++ CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0
      - name: submodule update
        run: git submodule update --init --recursive
      - name: Install dependents
        run: |
          sudo apt install autopoint libcurl4-gnutls-dev libgmp-dev libsodium-dev libupnp-dev libxmlrpc-core-c3-dev uuid-dev libcunit1-dev libjson-c-dev libtommath-dev libtomcrypt-dev mingw-w64
      - name: autogen.sh
        run: ./autogen.sh
      - name: configure
        run: mkdir bin && cd bin && ../configure
      - name: configure
        run: mkdir crossbuild && cd crossbuild && ../configure --host x86_64-w64-mingw32
      - name: make
        run: make -C bin
      - name: make check
        run: make check -C bin
      - name: make distcheck
        run: make distcheck -C bin
      - name: Save artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: study.tar.gz
          path: bin/study-1.0.2-alpha.tar.gz
