name: C/C++ CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependents
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
          sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
          sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
          sudo apt-get update
          sudo apt install libcurl4-gnutls-dev libgmp-dev libsodium-dev libxmlrpc-core-c3-dev uuid-dev cuda-10-2 libupnp-dev
          bash -c "/usr/bin/lspci | grep -i nvidia"
      - name: autogen.sh
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: PATH=/usr/local/cuda-10.2/bin:${PATH} make -j
      - name: test cudamalloctest
        run: ./src/cudamalloctest
      - name: make check
        run: PATH=/usr/local/cuda-10.2/bin:${PATH} make check -j
      - name: make distcheck
        run: PATH=/usr/local/cuda-10.2/bin:${PATH} make distcheck -j
      - name: make dist
        run: PATH=/usr/local/cuda-10.2/bin:${PATH} make dist -j
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: study-1.0.0-rc4.tar.gz
          path: study-1.0.0-rc4.tar.gz
